[connections.db_mysql]
dialect = "mysql"
driver = "mysqlconnector" # Asegúrese de tener 'mysql-connector-python' instalado
host = "qanh131.dedalogestion.net"
port = 3306
database = "qanh131"
username = "qaop422"
password = "!V9e_rka9-N484Q"

# Opcional: Configuración de SSL (si su MySQL lo requiere)
# ssl_args = { "ssl_ca": "/path/to/ca.pem" }

